# Default values for vpn-commander
replicaCount: 1

image:
  repository: ghcr.io/staners2/vpn-commander
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Environment variables configuration
env:
  # Router SSH Configuration  
  ROUTER_HOST: "192.168.1.1"
  ROUTER_USERNAME: "admin"
  
  # Optional: Custom Xray config path
  XRAY_CONFIG_PATH: "/opt/etc/xray/configs/05_routing.json"
  
  # Logging configuration
  LOG_LEVEL: "info"
  
  # Telegram Bot Token from @BotFather - configure this value
  TELEGRAM_BOT_TOKEN: "your_bot_token_here"
  
  # Authorization code for bot access - configure this value
  AUTH_CODE: "your_secure_auth_code"
  
  # Router SSH password - configure this value
  ROUTER_PASSWORD: "your_router_password"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

# Service configuration (for health checks if needed)
service:
  enabled: false
  type: ClusterIP
  port: 8080

# Health checks configuration
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress:
    - to: []
      ports:
      - protocol: TCP
        port: 443  # HTTPS for Telegram API
      - protocol: TCP
        port: 22   # SSH to router

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1